#!/bin/bash
#
#all commands that start with SBATCH contain commands that are just used by SLURM for scheduling
#################
#set a job name
#SBATCH --job-name=ADsimulation
#################
#a file for job output, you can check job progress
#SBATCH --output=ADsim.out
#################
# a file for errors from the job
#SBATCH --error=ADsim.err
#################
#time you think you need; default is one hour
#in minutes in this case
#SBATCH --time=24:00:00
#################
#quality of service; think of it as job priority
#SBATCH --qos=normal
#################
#number of nodes you are requesting
#SBATCH --nodes=2
#################
#memory per node; default is 4000 MB per CPU
#SBATCH --mem=4000
#you could use --mem-per-cpu; they mean what we are calling cores
#################
#tasks to run per node; a "task" is usually mapped to a MPI processes.
# for local parallelism (OpenMP or threads), use "--ntasks-per-node=1 --cpus-per-tasks=16" instead
#SBATCH --ntasks-per-node=24
#################
#partition to use
#SBATCH --partition=amarsden
#################

#Method 1
module load openmpi/1.10.2/gcc

#Method 2
#module load mpich/3.1.4/intel
#module load openmpi/1.8.7/gcc
#module load intel/13sp1up1

#run with mpirun
#srun ~/SimVascular_Dec2015/BuildWithMake/Bin/flowsolver-gcc-gfortran-openmpi.exe
srun ~/ADsolver/trunk/bin/memTransport fParam.ini
